/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LiteSnacks;

import javafx.application.Application;
import javafx.stage.Stage;

import LiteSnacks.UI.LoginScene;

public class App extends Application{

    @Override
    public void start(Stage primaryStage) throws Exception {

        primaryStage.setTitle("Vending machine");
        LoginScene loginScene = new LoginScene(600,400,primaryStage);
        loginScene.setScene();
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}